

server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 123456


application:
  jwt:
      secret-key: harryPotterharryPotterharryPotterharryPotterharryPotterharryPotter
      tokenPrefix: tokenPrefix
      tokenExpirationAfterDays: 10
#      expire-length: 864000000 # 10 days duration by default: 10*24*60 minutes * 60 seconds * 1000 miliseconds


